#!/bin/bash

echo "Testing Ctrl+T preview functionality in Session Viewer"
echo "=================================================="
echo ""
echo "Instructions to test manually:"
echo "1. Run: cargo run --release"
echo "2. In Search screen: Type a query to get some results"
echo "3. Press Ctrl+S to enter Session Viewer"
echo "4. Press Ctrl+T to toggle preview"
echo "5. Check debug.log to see if the key event is properly handled"
echo ""
echo "Expected behavior:"
echo "- In Search screen: Ctrl+T should toggle preview (showing message details on the right)"
echo "- In Session Viewer: Ctrl+T should also toggle preview"
echo "- Debug log should show: 'Ctrl+T pressed in mode SessionViewer, sending ToggleSessionPreview'"
echo ""
echo "The fix has been applied to src/interactive_ratatui/mod.rs:"
echo "- Global Ctrl+T handler now checks the current mode"
echo "- Sends Message::TogglePreview for Search mode"
echo "- Sends Message::ToggleSessionPreview for SessionViewer mode"